"""
Populate sparse API maps (graph nodes/edges) for all packages.
Packages with 0-2 nodes get a full hand-crafted API map.
"""
import json
import os

DATA_DIR = os.path.join(os.path.dirname(__file__), "../public/data/packages")

GRAPHS = {
    "requests": {
        "nodes": [
            {"id": "requests", "type": "module", "label": "requests", "summary": "Top-level module. Import as `import requests`.", "difficulty": 1, "tags": ["entry-point"]},
            {"id": "get", "type": "function", "label": "requests.get()", "summary": "Send a GET request. Returns a Response object.", "difficulty": 1, "tags": ["http", "common"]},
            {"id": "post", "type": "function", "label": "requests.post()", "summary": "Send a POST request with optional JSON/form body.", "difficulty": 1, "tags": ["http", "common"]},
            {"id": "put", "type": "function", "label": "requests.put()", "summary": "Send a PUT request to update a resource.", "difficulty": 1, "tags": ["http"]},
            {"id": "delete", "type": "function", "label": "requests.delete()", "summary": "Send a DELETE request.", "difficulty": 1, "tags": ["http"]},
            {"id": "patch", "type": "function", "label": "requests.patch()", "summary": "Send a PATCH request for partial updates.", "difficulty": 1, "tags": ["http"]},
            {"id": "head", "type": "function", "label": "requests.head()", "summary": "Send a HEAD request (headers only, no body).", "difficulty": 2, "tags": ["http"]},
            {"id": "Session", "type": "class", "label": "Session", "summary": "Persistent session that shares headers, cookies, and connection pool across requests.", "difficulty": 2, "tags": ["session", "common"]},
            {"id": "Response", "type": "class", "label": "Response", "summary": "HTTP response object. Key attrs: .status_code, .text, .json(), .content, .headers.", "difficulty": 1, "tags": ["response"]},
            {"id": "Request", "type": "class", "label": "Request", "summary": "Represents a prepared HTTP request before sending.", "difficulty": 2, "tags": ["advanced"]},
            {"id": "PreparedRequest", "type": "class", "label": "PreparedRequest", "summary": "A fully prepared request ready to be sent via Session.send().", "difficulty": 3, "tags": ["advanced"]},
            {"id": "auth", "type": "module", "label": "requests.auth", "summary": "Auth helpers: HTTPBasicAuth, HTTPDigestAuth, AuthBase for custom auth.", "difficulty": 2, "tags": ["auth"]},
            {"id": "exceptions", "type": "module", "label": "requests.exceptions", "summary": "Exception hierarchy: RequestException, ConnectionError, Timeout, HTTPError, TooManyRedirects.", "difficulty": 2, "tags": ["error-handling"]},
            {"id": "adapters", "type": "module", "label": "requests.adapters", "summary": "HTTPAdapter for configuring retries, pool size, and SSL.", "difficulty": 3, "tags": ["advanced"]},
        ],
        "edges": [
            {"id": "e1", "from": "requests", "to": "get", "label": "contains"},
            {"id": "e2", "from": "requests", "to": "post", "label": "contains"},
            {"id": "e3", "from": "requests", "to": "put", "label": "contains"},
            {"id": "e4", "from": "requests", "to": "delete", "label": "contains"},
            {"id": "e5", "from": "requests", "to": "patch", "label": "contains"},
            {"id": "e6", "from": "requests", "to": "head", "label": "contains"},
            {"id": "e7", "from": "requests", "to": "Session", "label": "contains"},
            {"id": "e8", "from": "requests", "to": "Response", "label": "contains"},
            {"id": "e9", "from": "requests", "to": "auth", "label": "contains"},
            {"id": "e10", "from": "requests", "to": "exceptions", "label": "contains"},
            {"id": "e11", "from": "requests", "to": "adapters", "label": "contains"},
            {"id": "e12", "from": "get", "to": "Response", "label": "returns"},
            {"id": "e13", "from": "post", "to": "Response", "label": "returns"},
            {"id": "e14", "from": "Session", "to": "adapters", "label": "uses"},
        ],
    },

    "numpy": {
        "nodes": [
            {"id": "numpy", "type": "module", "label": "numpy", "summary": "Top-level module. Convention: `import numpy as np`.", "difficulty": 1, "tags": ["entry-point"]},
            {"id": "ndarray", "type": "class", "label": "ndarray", "summary": "N-dimensional array — the core data structure. Supports vectorized operations, slicing, broadcasting.", "difficulty": 1, "tags": ["array", "common"]},
            {"id": "array", "type": "function", "label": "np.array()", "summary": "Create an ndarray from a list or nested list.", "difficulty": 1, "tags": ["creation"]},
            {"id": "zeros", "type": "function", "label": "np.zeros() / np.ones()", "summary": "Create arrays filled with 0s or 1s of a given shape.", "difficulty": 1, "tags": ["creation"]},
            {"id": "arange", "type": "function", "label": "np.arange() / np.linspace()", "summary": "Generate evenly spaced values (step-based or count-based).", "difficulty": 1, "tags": ["creation"]},
            {"id": "random", "type": "module", "label": "np.random", "summary": "Random number generation: rand, randn, randint, seed, default_rng.", "difficulty": 2, "tags": ["random"]},
            {"id": "linalg", "type": "module", "label": "np.linalg", "summary": "Linear algebra: dot, inv, eig, svd, norm, solve.", "difficulty": 3, "tags": ["math"]},
            {"id": "math_funcs", "type": "function", "label": "Ufuncs (np.sin, np.exp, np.sqrt…)", "summary": "Universal functions that apply element-wise to arrays with broadcasting.", "difficulty": 2, "tags": ["math", "common"]},
            {"id": "reshape", "type": "function", "label": "ndarray.reshape() / np.reshape()", "summary": "Change array shape without copying data. Use -1 for automatic dimension.", "difficulty": 2, "tags": ["shape"]},
            {"id": "concatenate", "type": "function", "label": "np.concatenate() / np.stack()", "summary": "Join arrays along existing or new axes.", "difficulty": 2, "tags": ["shape"]},
            {"id": "indexing", "type": "concept", "label": "Fancy Indexing & Boolean Masks", "summary": "Select elements with boolean arrays (arr[arr > 0]) or integer index arrays.", "difficulty": 2, "tags": ["indexing"]},
            {"id": "dtype", "type": "concept", "label": "dtype", "summary": "Data type of array elements (float64, int32, bool, etc). Controls memory and precision.", "difficulty": 2, "tags": ["dtype"]},
        ],
        "edges": [
            {"id": "e1", "from": "numpy", "to": "ndarray", "label": "core"},
            {"id": "e2", "from": "numpy", "to": "array", "label": "contains"},
            {"id": "e3", "from": "numpy", "to": "zeros", "label": "contains"},
            {"id": "e4", "from": "numpy", "to": "arange", "label": "contains"},
            {"id": "e5", "from": "numpy", "to": "random", "label": "contains"},
            {"id": "e6", "from": "numpy", "to": "linalg", "label": "contains"},
            {"id": "e7", "from": "numpy", "to": "math_funcs", "label": "contains"},
            {"id": "e8", "from": "array", "to": "ndarray", "label": "returns"},
            {"id": "e9", "from": "ndarray", "to": "reshape", "label": "method"},
            {"id": "e10", "from": "ndarray", "to": "indexing", "label": "supports"},
            {"id": "e11", "from": "ndarray", "to": "dtype", "label": "has"},
            {"id": "e12", "from": "numpy", "to": "concatenate", "label": "contains"},
        ],
    },

    "pandas": {
        "nodes": [
            {"id": "pandas", "type": "module", "label": "pandas", "summary": "Top-level module. Convention: `import pandas as pd`.", "difficulty": 1, "tags": ["entry-point"]},
            {"id": "DataFrame", "type": "class", "label": "DataFrame", "summary": "2D labeled table — rows × columns. The primary pandas data structure.", "difficulty": 1, "tags": ["core", "common"]},
            {"id": "Series", "type": "class", "label": "Series", "summary": "1D labeled array. Each column in a DataFrame is a Series.", "difficulty": 1, "tags": ["core", "common"]},
            {"id": "Index", "type": "class", "label": "Index / MultiIndex", "summary": "Row/column labels. MultiIndex enables hierarchical indexing.", "difficulty": 2, "tags": ["index"]},
            {"id": "read_csv", "type": "function", "label": "pd.read_csv() / pd.read_json()", "summary": "Load data from CSV, JSON, Excel, Parquet, SQL into a DataFrame.", "difficulty": 1, "tags": ["io", "common"]},
            {"id": "groupby", "type": "function", "label": "DataFrame.groupby()", "summary": "Split-apply-combine: group rows by key, apply aggregation (sum, mean, count).", "difficulty": 2, "tags": ["agg", "common"]},
            {"id": "merge", "type": "function", "label": "pd.merge() / DataFrame.join()", "summary": "SQL-style joins (inner, left, right, outer) on one or more key columns.", "difficulty": 2, "tags": ["join"]},
            {"id": "loc_iloc", "type": "concept", "label": ".loc[] and .iloc[]", "summary": ".loc selects by label, .iloc by integer position. Both support slicing and boolean masks.", "difficulty": 2, "tags": ["indexing"]},
            {"id": "apply", "type": "function", "label": "DataFrame.apply()", "summary": "Apply a function along rows (axis=1) or columns (axis=0).", "difficulty": 2, "tags": ["transform"]},
            {"id": "pivot", "type": "function", "label": "DataFrame.pivot_table()", "summary": "Reshape data: rows become columns. Similar to Excel pivot tables.", "difficulty": 3, "tags": ["reshape"]},
            {"id": "na", "type": "concept", "label": "NaN / NA handling", "summary": "dropna(), fillna(), isna() — manage missing values represented as NaN.", "difficulty": 2, "tags": ["cleaning"]},
            {"id": "dtypes", "type": "concept", "label": "dtypes & Categorical", "summary": "Column data types. Use CategoricalDtype to reduce memory for string columns.", "difficulty": 2, "tags": ["dtype"]},
        ],
        "edges": [
            {"id": "e1", "from": "pandas", "to": "DataFrame", "label": "core"},
            {"id": "e2", "from": "pandas", "to": "Series", "label": "core"},
            {"id": "e3", "from": "pandas", "to": "read_csv", "label": "contains"},
            {"id": "e4", "from": "pandas", "to": "merge", "label": "contains"},
            {"id": "e5", "from": "DataFrame", "to": "Series", "label": "column-is"},
            {"id": "e6", "from": "DataFrame", "to": "groupby", "label": "method"},
            {"id": "e7", "from": "DataFrame", "to": "loc_iloc", "label": "method"},
            {"id": "e8", "from": "DataFrame", "to": "apply", "label": "method"},
            {"id": "e9", "from": "DataFrame", "to": "pivot", "label": "method"},
            {"id": "e10", "from": "DataFrame", "to": "na", "label": "method"},
            {"id": "e11", "from": "DataFrame", "to": "dtypes", "label": "has"},
            {"id": "e12", "from": "read_csv", "to": "DataFrame", "label": "returns"},
        ],
    },

    "fastapi": {
        "nodes": [
            {"id": "fastapi", "type": "module", "label": "fastapi", "summary": "Top-level module. Import FastAPI, APIRouter, Depends, etc.", "difficulty": 1, "tags": ["entry-point"]},
            {"id": "FastAPI", "type": "class", "label": "FastAPI", "summary": "Main application class. Create with `app = FastAPI()`. Mount routers, middleware, lifecycle hooks.", "difficulty": 1, "tags": ["core", "common"]},
            {"id": "APIRouter", "type": "class", "label": "APIRouter", "summary": "Group related endpoints into a router, then include in the app with app.include_router().", "difficulty": 2, "tags": ["routing"]},
            {"id": "path_ops", "type": "concept", "label": "Path Operations (@app.get, @app.post…)", "summary": "Decorators that register route handlers: get, post, put, delete, patch.", "difficulty": 1, "tags": ["routing", "common"]},
            {"id": "Depends", "type": "function", "label": "Depends()", "summary": "Dependency injection. Pass functions as deps — FastAPI calls them and injects their return value.", "difficulty": 2, "tags": ["di", "common"]},
            {"id": "Body", "type": "function", "label": "Body / Query / Path / Header", "summary": "Declare request parameters with metadata, validation, and aliases.", "difficulty": 2, "tags": ["params"]},
            {"id": "BaseModel", "type": "class", "label": "Pydantic BaseModel (via fastapi)", "summary": "Request/response schemas. FastAPI auto-validates, parses, and documents them.", "difficulty": 1, "tags": ["schema", "common"]},
            {"id": "HTTPException", "type": "class", "label": "HTTPException", "summary": "Raise HTTP errors: `raise HTTPException(status_code=404, detail='Not found')`.", "difficulty": 1, "tags": ["error"]},
            {"id": "BackgroundTasks", "type": "class", "label": "BackgroundTasks", "summary": "Run tasks after returning response (email, logging) without blocking.", "difficulty": 2, "tags": ["async"]},
            {"id": "middleware", "type": "concept", "label": "Middleware (@app.middleware)", "summary": "Intercept requests/responses globally. Used for CORS, auth, logging, timing.", "difficulty": 3, "tags": ["middleware"]},
            {"id": "lifespan", "type": "concept", "label": "Lifespan (startup/shutdown)", "summary": "async context manager for startup/shutdown logic (DB pool, ML model load).", "difficulty": 2, "tags": ["lifecycle"]},
            {"id": "openapi", "type": "concept", "label": "Auto OpenAPI / Swagger UI", "summary": "FastAPI generates /docs (Swagger) and /redoc automatically from type hints.", "difficulty": 1, "tags": ["docs"]},
        ],
        "edges": [
            {"id": "e1", "from": "fastapi", "to": "FastAPI", "label": "contains"},
            {"id": "e2", "from": "fastapi", "to": "APIRouter", "label": "contains"},
            {"id": "e3", "from": "fastapi", "to": "Depends", "label": "contains"},
            {"id": "e4", "from": "fastapi", "to": "HTTPException", "label": "contains"},
            {"id": "e5", "from": "fastapi", "to": "BackgroundTasks", "label": "contains"},
            {"id": "e6", "from": "FastAPI", "to": "path_ops", "label": "uses"},
            {"id": "e7", "from": "FastAPI", "to": "middleware", "label": "supports"},
            {"id": "e8", "from": "FastAPI", "to": "lifespan", "label": "supports"},
            {"id": "e9", "from": "FastAPI", "to": "openapi", "label": "generates"},
            {"id": "e10", "from": "path_ops", "to": "BaseModel", "label": "validates-with"},
            {"id": "e11", "from": "path_ops", "to": "Depends", "label": "uses"},
            {"id": "e12", "from": "path_ops", "to": "Body", "label": "uses"},
            {"id": "e13", "from": "APIRouter", "to": "FastAPI", "label": "mounted-in"},
        ],
    },

    "flask": {
        "nodes": [
            {"id": "flask", "type": "module", "label": "flask", "summary": "Top-level module. Import Flask, render_template, request, etc.", "difficulty": 1, "tags": ["entry-point"]},
            {"id": "Flask", "type": "class", "label": "Flask", "summary": "Application factory: `app = Flask(__name__)`. Registers routes, extensions, config.", "difficulty": 1, "tags": ["core", "common"]},
            {"id": "route", "type": "concept", "label": "@app.route()", "summary": "Decorator that binds a URL pattern to a view function. Supports variable rules like <int:id>.", "difficulty": 1, "tags": ["routing", "common"]},
            {"id": "Blueprint", "type": "class", "label": "Blueprint", "summary": "Modular component for splitting app into reusable route groups. Register with app.register_blueprint().", "difficulty": 2, "tags": ["routing"]},
            {"id": "request", "type": "object", "label": "request (context local)", "summary": "Current HTTP request: request.args, request.form, request.json, request.files.", "difficulty": 1, "tags": ["context", "common"]},
            {"id": "g", "type": "object", "label": "g (application context)", "summary": "Request-scoped storage for sharing data across functions (e.g. db connection).", "difficulty": 2, "tags": ["context"]},
            {"id": "session", "type": "object", "label": "session (cookie-based)", "summary": "Dict-like session backed by a signed cookie. Store small user state.", "difficulty": 2, "tags": ["session"]},
            {"id": "render_template", "type": "function", "label": "render_template()", "summary": "Render a Jinja2 template and return an HTML response.", "difficulty": 1, "tags": ["templates"]},
            {"id": "jsonify", "type": "function", "label": "jsonify()", "summary": "Convert a dict to a JSON response with the correct Content-Type header.", "difficulty": 1, "tags": ["response"]},
            {"id": "abort", "type": "function", "label": "abort() / make_response()", "summary": "abort() raises HTTP errors; make_response() builds custom responses.", "difficulty": 2, "tags": ["response"]},
            {"id": "before_after", "type": "concept", "label": "@before_request / @after_request", "summary": "Run code before/after every request (auth checks, response headers).", "difficulty": 2, "tags": ["hooks"]},
            {"id": "extensions", "type": "concept", "label": "Flask Extensions", "summary": "Ecosystem: Flask-SQLAlchemy, Flask-Login, Flask-Migrate, Flask-WTF, Flask-JWT-Extended.", "difficulty": 2, "tags": ["ecosystem"]},
        ],
        "edges": [
            {"id": "e1", "from": "flask", "to": "Flask", "label": "contains"},
            {"id": "e2", "from": "flask", "to": "request", "label": "contains"},
            {"id": "e3", "from": "flask", "to": "g", "label": "contains"},
            {"id": "e4", "from": "flask", "to": "session", "label": "contains"},
            {"id": "e5", "from": "flask", "to": "render_template", "label": "contains"},
            {"id": "e6", "from": "flask", "to": "jsonify", "label": "contains"},
            {"id": "e7", "from": "Flask", "to": "route", "label": "uses"},
            {"id": "e8", "from": "Flask", "to": "Blueprint", "label": "registers"},
            {"id": "e9", "from": "Flask", "to": "before_after", "label": "supports"},
            {"id": "e10", "from": "Flask", "to": "extensions", "label": "supports"},
            {"id": "e11", "from": "route", "to": "render_template", "label": "calls"},
            {"id": "e12", "from": "route", "to": "jsonify", "label": "calls"},
        ],
    },

    "express": {
        "nodes": [
            {"id": "express", "type": "module", "label": "express", "summary": "Default export is the factory function: `const app = express()`.", "difficulty": 1, "tags": ["entry-point"]},
            {"id": "app", "type": "object", "label": "app (Express instance)", "summary": "The application object. Register routes, middleware, settings. Call app.listen() to start.", "difficulty": 1, "tags": ["core", "common"]},
            {"id": "Router", "type": "class", "label": "express.Router()", "summary": "Mini-app for grouping related routes. Mount with app.use('/prefix', router).", "difficulty": 2, "tags": ["routing"]},
            {"id": "routing", "type": "concept", "label": "Route Methods (app.get, app.post…)", "summary": "app.get(), app.post(), app.put(), app.delete() bind URL patterns to handlers.", "difficulty": 1, "tags": ["routing", "common"]},
            {"id": "middleware", "type": "concept", "label": "Middleware (app.use)", "summary": "Functions with (req, res, next). Process requests in sequence: logging, auth, body parsing.", "difficulty": 2, "tags": ["middleware", "common"]},
            {"id": "Request", "type": "object", "label": "req (Request)", "summary": "req.params, req.query, req.body, req.headers, req.cookies.", "difficulty": 1, "tags": ["request"]},
            {"id": "Response", "type": "object", "label": "res (Response)", "summary": "res.json(), res.send(), res.status(), res.redirect(), res.render().", "difficulty": 1, "tags": ["response"]},
            {"id": "static", "type": "function", "label": "express.static()", "summary": "Serve static files from a directory.", "difficulty": 1, "tags": ["static"]},
            {"id": "json_mw", "type": "function", "label": "express.json() / express.urlencoded()", "summary": "Built-in body parsers for JSON and form-encoded request bodies.", "difficulty": 1, "tags": ["middleware", "common"]},
            {"id": "error_handler", "type": "concept", "label": "Error-handling Middleware", "summary": "4-arg middleware (err, req, res, next) handles errors thrown in route handlers.", "difficulty": 2, "tags": ["error"]},
        ],
        "edges": [
            {"id": "e1", "from": "express", "to": "app", "label": "creates"},
            {"id": "e2", "from": "express", "to": "Router", "label": "contains"},
            {"id": "e3", "from": "express", "to": "static", "label": "contains"},
            {"id": "e4", "from": "express", "to": "json_mw", "label": "contains"},
            {"id": "e5", "from": "app", "to": "routing", "label": "uses"},
            {"id": "e6", "from": "app", "to": "middleware", "label": "uses"},
            {"id": "e7", "from": "routing", "to": "Request", "label": "receives"},
            {"id": "e8", "from": "routing", "to": "Response", "label": "sends"},
            {"id": "e9", "from": "app", "to": "error_handler", "label": "uses"},
            {"id": "e10", "from": "Router", "to": "app", "label": "mounted-in"},
        ],
    },

    "lodash": {
        "nodes": [
            {"id": "lodash", "type": "module", "label": "lodash", "summary": "Import as `import _ from 'lodash'` or cherry-pick: `import chunk from 'lodash/chunk'`.", "difficulty": 1, "tags": ["entry-point"]},
            {"id": "array", "type": "concept", "label": "Array Utilities", "summary": "chunk, compact, difference, flatten, flattenDeep, intersection, union, uniq, zip, take, drop.", "difficulty": 1, "tags": ["array", "common"]},
            {"id": "collection", "type": "concept", "label": "Collection Methods", "summary": "filter, find, findIndex, map, reduce, forEach, groupBy, sortBy, orderBy, countBy, keyBy.", "difficulty": 1, "tags": ["collection", "common"]},
            {"id": "object", "type": "concept", "label": "Object Utilities", "summary": "assign, merge, cloneDeep, pick, omit, has, get, set, keys, values, entries, mapKeys, mapValues.", "difficulty": 1, "tags": ["object", "common"]},
            {"id": "string", "type": "concept", "label": "String Utilities", "summary": "camelCase, kebabCase, snakeCase, capitalize, trim, truncate, escape, pad, repeat, template.", "difficulty": 1, "tags": ["string"]},
            {"id": "function_utils", "type": "concept", "label": "Function Utilities", "summary": "debounce, throttle, memoize, once, partial, curry, bind, flip, negate, wrap.", "difficulty": 2, "tags": ["function", "common"]},
            {"id": "math", "type": "concept", "label": "Math Utilities", "summary": "add, subtract, multiply, divide, ceil, floor, round, clamp, inRange, random, sum, sumBy, mean.", "difficulty": 1, "tags": ["math"]},
            {"id": "lang", "type": "concept", "label": "Lang / Type Checks", "summary": "isArray, isObject, isString, isNumber, isNil, isEqual, isEmpty, cloneDeep, toArray, toNumber.", "difficulty": 2, "tags": ["type-check"]},
            {"id": "chain", "type": "concept", "label": "_.chain() / Lazy Evaluation", "summary": "Wrap a value in a chain to compose operations. Call .value() to execute.", "difficulty": 3, "tags": ["advanced"]},
        ],
        "edges": [
            {"id": "e1", "from": "lodash", "to": "array", "label": "contains"},
            {"id": "e2", "from": "lodash", "to": "collection", "label": "contains"},
            {"id": "e3", "from": "lodash", "to": "object", "label": "contains"},
            {"id": "e4", "from": "lodash", "to": "string", "label": "contains"},
            {"id": "e5", "from": "lodash", "to": "function_utils", "label": "contains"},
            {"id": "e6", "from": "lodash", "to": "math", "label": "contains"},
            {"id": "e7", "from": "lodash", "to": "lang", "label": "contains"},
            {"id": "e8", "from": "lodash", "to": "chain", "label": "contains"},
            {"id": "e9", "from": "collection", "to": "array", "label": "works-on"},
        ],
    },

    "dayjs": {
        "nodes": [
            {"id": "dayjs", "type": "module", "label": "dayjs", "summary": "Default export is the factory: `dayjs()` returns an immutable Day.js object.", "difficulty": 1, "tags": ["entry-point"]},
            {"id": "factory", "type": "function", "label": "dayjs(input?)", "summary": "Parse a date: dayjs(), dayjs('2024-01-01'), dayjs(Date), dayjs(timestamp).", "difficulty": 1, "tags": ["parsing", "common"]},
            {"id": "Dayjs", "type": "class", "label": "Dayjs (immutable)", "summary": "Immutable date object. All manipulation methods return a new Dayjs instance.", "difficulty": 1, "tags": ["core"]},
            {"id": "format", "type": "function", "label": ".format(template)", "summary": "Format a date: dayjs().format('YYYY-MM-DD HH:mm:ss'). Tokens: YYYY, MM, DD, HH, mm, ss, ddd.", "difficulty": 1, "tags": ["format", "common"]},
            {"id": "manipulation", "type": "concept", "label": "Manipulation (.add, .subtract, .set)", "summary": ".add(1, 'day'), .subtract(2, 'month'), .startOf('week'), .endOf('year').", "difficulty": 1, "tags": ["manipulation", "common"]},
            {"id": "display", "type": "concept", "label": "Display (.toDate, .toISOString, .unix)", "summary": ".toDate() → JS Date, .toISOString(), .valueOf() → ms timestamp, .unix() → seconds.", "difficulty": 1, "tags": ["display"]},
            {"id": "query", "type": "concept", "label": "Query (.isBefore, .isAfter, .isSame)", "summary": "Compare dates: .isBefore(other), .isAfter(other), .isSame(other, 'month').", "difficulty": 1, "tags": ["compare"]},
            {"id": "diff", "type": "function", "label": ".diff()", "summary": ".diff(other, 'day') returns numeric difference in given unit.", "difficulty": 2, "tags": ["compare"]},
            {"id": "plugins", "type": "concept", "label": "Plugins (extend)", "summary": "dayjs.extend(plugin) adds functionality: relativeTime, utc, timezone, duration, isBetween, weekday.", "difficulty": 2, "tags": ["plugins", "common"]},
            {"id": "utc", "type": "concept", "label": "UTC & Timezone Plugin", "summary": "dayjs.extend(utc); dayjs.extend(timezone). Use .utc() and .tz('America/New_York').", "difficulty": 2, "tags": ["timezone"]},
            {"id": "locale", "type": "concept", "label": "Locale (i18n)", "summary": "import 'dayjs/locale/fr'; dayjs.locale('fr'). Affects .format() day/month names.", "difficulty": 2, "tags": ["i18n"]},
        ],
        "edges": [
            {"id": "e1", "from": "dayjs", "to": "factory", "label": "exports"},
            {"id": "e2", "from": "factory", "to": "Dayjs", "label": "returns"},
            {"id": "e3", "from": "Dayjs", "to": "format", "label": "method"},
            {"id": "e4", "from": "Dayjs", "to": "manipulation", "label": "method"},
            {"id": "e5", "from": "Dayjs", "to": "display", "label": "method"},
            {"id": "e6", "from": "Dayjs", "to": "query", "label": "method"},
            {"id": "e7", "from": "Dayjs", "to": "diff", "label": "method"},
            {"id": "e8", "from": "dayjs", "to": "plugins", "label": "supports"},
            {"id": "e9", "from": "plugins", "to": "utc", "label": "includes"},
            {"id": "e10", "from": "plugins", "to": "locale", "label": "includes"},
            {"id": "e11", "from": "manipulation", "to": "Dayjs", "label": "returns"},
        ],
    },

    "sharp": {
        "nodes": [
            {"id": "sharp", "type": "module", "label": "sharp", "summary": "Factory function: `sharp(input?)` starts a transform pipeline.", "difficulty": 1, "tags": ["entry-point"]},
            {"id": "factory", "type": "function", "label": "sharp(input, options?)", "summary": "Create a pipeline from a file path, Buffer, or stream. Options: animated, limitInputPixels.", "difficulty": 1, "tags": ["creation", "common"]},
            {"id": "Sharp", "type": "class", "label": "Sharp (pipeline)", "summary": "Chainable transform pipeline. Each method returns `this` for chaining.", "difficulty": 1, "tags": ["core"]},
            {"id": "resize", "type": "function", "label": ".resize(width, height, options)", "summary": "Resize image. fit: cover/contain/fill/inside/outside. withoutEnlargement, position.", "difficulty": 1, "tags": ["transform", "common"]},
            {"id": "format", "type": "concept", "label": "Output Format (.jpeg, .png, .webp, .avif)", "summary": ".jpeg({quality:80}), .png(), .webp(), .avif(), .tiff(), .gif() — set output format and options.", "difficulty": 1, "tags": ["output", "common"]},
            {"id": "composite", "type": "function", "label": ".composite(overlays)", "summary": "Overlay images: watermarks, text, shape layers. Each overlay has input, gravity/top/left.", "difficulty": 2, "tags": ["composite"]},
            {"id": "colour", "type": "concept", "label": "Colour Operations", "summary": ".greyscale(), .tint(colour), .modulate({brightness, saturation, hue}), .negate(), .gamma().", "difficulty": 2, "tags": ["colour"]},
            {"id": "metadata", "type": "function", "label": ".metadata()", "summary": "Read image metadata asynchronously: width, height, format, channels, space, density, exif.", "difficulty": 1, "tags": ["info"]},
            {"id": "crop", "type": "function", "label": ".extract() / .trim()", "summary": ".extract({left,top,width,height}) crops a region. .trim() removes border pixels.", "difficulty": 2, "tags": ["transform"]},
            {"id": "text", "type": "function", "label": "Text Overlay (via SVG)", "summary": "No native text API; use SVG buffer as composite input to render text onto images.", "difficulty": 3, "tags": ["text"]},
            {"id": "pipeline", "type": "concept", "label": "Stream / Buffer Pipeline", "summary": ".toBuffer() → Promise<Buffer>, .toFile(path) → writes to disk, .pipe(stream) for streaming.", "difficulty": 2, "tags": ["output"]},
        ],
        "edges": [
            {"id": "e1", "from": "sharp", "to": "factory", "label": "exports"},
            {"id": "e2", "from": "factory", "to": "Sharp", "label": "returns"},
            {"id": "e3", "from": "Sharp", "to": "resize", "label": "method"},
            {"id": "e4", "from": "Sharp", "to": "format", "label": "method"},
            {"id": "e5", "from": "Sharp", "to": "composite", "label": "method"},
            {"id": "e6", "from": "Sharp", "to": "colour", "label": "method"},
            {"id": "e7", "from": "Sharp", "to": "metadata", "label": "method"},
            {"id": "e8", "from": "Sharp", "to": "crop", "label": "method"},
            {"id": "e9", "from": "Sharp", "to": "pipeline", "label": "method"},
            {"id": "e10", "from": "Sharp", "to": "text", "label": "supports"},
        ],
    },

    "ky": {
        "nodes": [
            {"id": "ky", "type": "module", "label": "ky", "summary": "Default export is the ky instance. Import as `import ky from 'ky'`.", "difficulty": 1, "tags": ["entry-point"]},
            {"id": "methods", "type": "function", "label": "ky.get / .post / .put / .delete / .patch", "summary": "HTTP methods returning a ResponsePromise. Chain .json(), .text(), .blob() to parse.", "difficulty": 1, "tags": ["http", "common"]},
            {"id": "ResponsePromise", "type": "class", "label": "ResponsePromise", "summary": "Extends Promise<Response>. Has .json<T>(), .text(), .arrayBuffer(), .blob() shorthand methods.", "difficulty": 1, "tags": ["response"]},
            {"id": "extend", "type": "function", "label": "ky.extend(defaults)", "summary": "Create a custom ky instance with preset options: prefixUrl, headers, timeout, hooks.", "difficulty": 2, "tags": ["config", "common"]},
            {"id": "hooks", "type": "concept", "label": "Hooks", "summary": "beforeRequest, afterResponse, beforeError, beforeRetry arrays for intercepting the request lifecycle.", "difficulty": 2, "tags": ["hooks"]},
            {"id": "retry", "type": "concept", "label": "Retry", "summary": "Built-in retry on network errors and 5xx. Options: count, limit, methods, statusCodes, backoffLimit.", "difficulty": 2, "tags": ["reliability"]},
            {"id": "timeout", "type": "concept", "label": "Timeout", "summary": "timeout option (ms). Throws TimeoutError. Set false to disable.", "difficulty": 1, "tags": ["reliability"]},
            {"id": "searchParams", "type": "concept", "label": "searchParams", "summary": "Pass an object/URLSearchParams for query string — auto-serialized, no manual string building.", "difficulty": 1, "tags": ["params"]},
        ],
        "edges": [
            {"id": "e1", "from": "ky", "to": "methods", "label": "contains"},
            {"id": "e2", "from": "methods", "to": "ResponsePromise", "label": "returns"},
            {"id": "e3", "from": "ky", "to": "extend", "label": "contains"},
            {"id": "e4", "from": "extend", "to": "ky", "label": "returns-new"},
            {"id": "e5", "from": "ky", "to": "hooks", "label": "supports"},
            {"id": "e6", "from": "ky", "to": "retry", "label": "supports"},
            {"id": "e7", "from": "ky", "to": "timeout", "label": "supports"},
            {"id": "e8", "from": "methods", "to": "searchParams", "label": "accepts"},
        ],
    },

    "aiohttp": {
        "nodes": [
            {"id": "aiohttp", "type": "module", "label": "aiohttp", "summary": "Async HTTP client/server framework. Import as `import aiohttp`.", "difficulty": 1, "tags": ["entry-point"]},
            {"id": "ClientSession", "type": "class", "label": "ClientSession", "summary": "The HTTP client. Create once per app with `async with aiohttp.ClientSession() as session:`. Reuse across requests.", "difficulty": 1, "tags": ["client", "common"]},
            {"id": "client_methods", "type": "concept", "label": "session.get / .post / .put / .delete", "summary": "HTTP methods. All are async context managers: `async with session.get(url) as resp:`.", "difficulty": 1, "tags": ["http", "common"]},
            {"id": "ClientResponse", "type": "class", "label": "ClientResponse", "summary": "Response object. .status, await .json(), await .text(), await .read() (bytes).", "difficulty": 1, "tags": ["response"]},
            {"id": "web", "type": "module", "label": "aiohttp.web", "summary": "Server-side: Application, RouteTableDef, Request, Response, run_app(). Build async web apps.", "difficulty": 2, "tags": ["server"]},
            {"id": "web_app", "type": "class", "label": "web.Application", "summary": "WSGI-like app object. Register routes, middleware, startup/cleanup signals.", "difficulty": 2, "tags": ["server"]},
            {"id": "web_request", "type": "class", "label": "web.Request", "summary": "Incoming server request: .match_info, await .json(), await .post(), .headers.", "difficulty": 2, "tags": ["server"]},
            {"id": "connector", "type": "class", "label": "TCPConnector", "summary": "Controls connection pooling: limit, limit_per_host, ssl, ttl_dns_cache.", "difficulty": 3, "tags": ["advanced"]},
            {"id": "timeout", "type": "class", "label": "ClientTimeout", "summary": "Timeout settings: total, connect, sock_read. Pass to ClientSession(timeout=...).", "difficulty": 2, "tags": ["reliability"]},
            {"id": "ws", "type": "concept", "label": "WebSocket Support", "summary": "session.ws_connect() for client WS; web.WebSocketResponse for server-side.", "difficulty": 3, "tags": ["websocket"]},
        ],
        "edges": [
            {"id": "e1", "from": "aiohttp", "to": "ClientSession", "label": "contains"},
            {"id": "e2", "from": "aiohttp", "to": "web", "label": "contains"},
            {"id": "e3", "from": "ClientSession", "to": "client_methods", "label": "method"},
            {"id": "e4", "from": "client_methods", "to": "ClientResponse", "label": "returns"},
            {"id": "e5", "from": "ClientSession", "to": "connector", "label": "uses"},
            {"id": "e6", "from": "ClientSession", "to": "timeout", "label": "accepts"},
            {"id": "e7", "from": "ClientSession", "to": "ws", "label": "supports"},
            {"id": "e8", "from": "web", "to": "web_app", "label": "contains"},
            {"id": "e9", "from": "web_app", "to": "web_request", "label": "receives"},
        ],
    },

    "anyio": {
        "nodes": [
            {"id": "anyio", "type": "module", "label": "anyio", "summary": "Async compatibility layer over asyncio and trio. Import as `import anyio`.", "difficulty": 1, "tags": ["entry-point"]},
            {"id": "run", "type": "function", "label": "anyio.run()", "summary": "Entry point: `anyio.run(main)`. Runs on asyncio or trio based on backend param.", "difficulty": 1, "tags": ["entry", "common"]},
            {"id": "task_group", "type": "function", "label": "anyio.create_task_group()", "summary": "Structured concurrency: spawn tasks, auto-cancel siblings on failure. `async with anyio.create_task_group() as tg: tg.start_soon(coro)`.", "difficulty": 2, "tags": ["concurrency", "common"]},
            {"id": "sleep", "type": "function", "label": "await anyio.sleep(seconds)", "summary": "Async sleep. Use sleep(0) to yield control.", "difficulty": 1, "tags": ["time"]},
            {"id": "move_on", "type": "function", "label": "move_on_after / fail_after", "summary": "Timeout scopes: move_on_after cancels silently, fail_after raises TimeoutError.", "difficulty": 2, "tags": ["timeout", "common"]},
            {"id": "streams", "type": "concept", "label": "Byte / Object Streams", "summary": "anyio.create_memory_object_stream() for in-process producer/consumer. Also TCP/Unix socket streams.", "difficulty": 2, "tags": ["io"]},
            {"id": "locks", "type": "concept", "label": "Synchronization Primitives", "summary": "Lock, Event, Semaphore, Condition, CapacityLimiter — compatible across asyncio/trio.", "difficulty": 2, "tags": ["sync"]},
            {"id": "to_thread", "type": "function", "label": "anyio.to_thread.run_sync()", "summary": "Run blocking code in a thread pool without blocking the event loop.", "difficulty": 2, "tags": ["threading", "common"]},
            {"id": "from_thread", "type": "function", "label": "anyio.from_thread.run()", "summary": "Call async code from a sync thread (started by to_thread.run_sync).", "difficulty": 3, "tags": ["threading"]},
        ],
        "edges": [
            {"id": "e1", "from": "anyio", "to": "run", "label": "contains"},
            {"id": "e2", "from": "anyio", "to": "task_group", "label": "contains"},
            {"id": "e3", "from": "anyio", "to": "sleep", "label": "contains"},
            {"id": "e4", "from": "anyio", "to": "move_on", "label": "contains"},
            {"id": "e5", "from": "anyio", "to": "streams", "label": "contains"},
            {"id": "e6", "from": "anyio", "to": "locks", "label": "contains"},
            {"id": "e7", "from": "anyio", "to": "to_thread", "label": "contains"},
            {"id": "e8", "from": "anyio", "to": "from_thread", "label": "contains"},
            {"id": "e9", "from": "task_group", "to": "move_on", "label": "combines-with"},
        ],
    },

    "pytest": {
        "nodes": [
            {"id": "pytest", "type": "module", "label": "pytest", "summary": "Import as `import pytest`. Run with `pytest` or `python -m pytest`.", "difficulty": 1, "tags": ["entry-point"]},
            {"id": "test_function", "type": "concept", "label": "Test Functions & Classes", "summary": "Any function starting with `test_` is auto-discovered. Group in `Test` classes (no __init__).", "difficulty": 1, "tags": ["discovery", "common"]},
            {"id": "assert", "type": "concept", "label": "assert Rewriting", "summary": "Use plain `assert`. pytest rewrites asserts to show rich diffs on failure. No need for assertEqual etc.", "difficulty": 1, "tags": ["assertions", "common"]},
            {"id": "fixtures", "type": "concept", "label": "Fixtures (@pytest.fixture)", "summary": "Dependency injection for tests. Yield for setup/teardown. Scopes: function, class, module, session.", "difficulty": 2, "tags": ["fixtures", "common"]},
            {"id": "parametrize", "type": "concept", "label": "@pytest.mark.parametrize", "summary": "Run a test with multiple input sets: @pytest.mark.parametrize('x,y', [(1,2),(3,4)]).", "difficulty": 2, "tags": ["parametrize", "common"]},
            {"id": "marks", "type": "concept", "label": "Marks (@pytest.mark.*)", "summary": "skip, skipif, xfail, filterwarnings, custom marks for filtering runs.", "difficulty": 2, "tags": ["marks"]},
            {"id": "raises", "type": "function", "label": "pytest.raises()", "summary": "Assert that code raises a specific exception: `with pytest.raises(ValueError):`.", "difficulty": 1, "tags": ["assertions", "common"]},
            {"id": "monkeypatch", "type": "fixture", "label": "monkeypatch fixture", "summary": "Temporarily replace attributes, environment variables, or dict items. Auto-undone after test.", "difficulty": 2, "tags": ["mocking"]},
            {"id": "tmp_path", "type": "fixture", "label": "tmp_path / tmp_path_factory", "summary": "Built-in fixture providing a temporary directory unique to the test invocation.", "difficulty": 2, "tags": ["fixtures"]},
            {"id": "capfd", "type": "fixture", "label": "capsys / capfd", "summary": "Capture stdout/stderr. Use .readouterr() to get output in assertions.", "difficulty": 2, "tags": ["capture"]},
            {"id": "conftest", "type": "concept", "label": "conftest.py", "summary": "Plugin file: define shared fixtures, hooks, and plugins. Auto-loaded by pytest from rootdir.", "difficulty": 2, "tags": ["config"]},
        ],
        "edges": [
            {"id": "e1", "from": "pytest", "to": "test_function", "label": "discovers"},
            {"id": "e2", "from": "pytest", "to": "fixtures", "label": "contains"},
            {"id": "e3", "from": "pytest", "to": "parametrize", "label": "contains"},
            {"id": "e4", "from": "pytest", "to": "marks", "label": "contains"},
            {"id": "e5", "from": "pytest", "to": "raises", "label": "contains"},
            {"id": "e6", "from": "test_function", "to": "assert", "label": "uses"},
            {"id": "e7", "from": "test_function", "to": "fixtures", "label": "injects"},
            {"id": "e8", "from": "fixtures", "to": "monkeypatch", "label": "includes"},
            {"id": "e9", "from": "fixtures", "to": "tmp_path", "label": "includes"},
            {"id": "e10", "from": "fixtures", "to": "capfd", "label": "includes"},
            {"id": "e11", "from": "conftest", "to": "fixtures", "label": "defines"},
        ],
    },

    "rich": {
        "nodes": [
            {"id": "rich", "type": "module", "label": "rich", "summary": "Import from rich: `from rich import print`, `from rich.console import Console`.", "difficulty": 1, "tags": ["entry-point"]},
            {"id": "Console", "type": "class", "label": "Console", "summary": "Main output object. `c = Console(); c.print('[bold red]Hello[/]')`. Controls width, file, markup.", "difficulty": 1, "tags": ["core", "common"]},
            {"id": "markup", "type": "concept", "label": "Rich Markup", "summary": "BBCode-like tags: [bold], [italic], [red], [link=url], [bold magenta on white]. Nesting supported.", "difficulty": 1, "tags": ["markup", "common"]},
            {"id": "Table", "type": "class", "label": "Table", "summary": "Render data as terminal tables. Add columns/rows, set styles, alignment, borders.", "difficulty": 1, "tags": ["display", "common"]},
            {"id": "Progress", "type": "class", "label": "Progress (progress bars)", "summary": "Live progress bars with spinners. track() wraps iterables. Custom columns.", "difficulty": 2, "tags": ["progress", "common"]},
            {"id": "Syntax", "type": "class", "label": "Syntax", "summary": "Syntax-highlighted code blocks via Pygments. `Syntax(code, 'python', theme='monokai')`.", "difficulty": 1, "tags": ["display"]},
            {"id": "Traceback", "type": "class", "label": "Traceback", "summary": "Beautiful exception tracebacks with local variable values. `install()` to replace default.", "difficulty": 2, "tags": ["debug"]},
            {"id": "Padding", "type": "class", "label": "Layout primitives (Panel, Padding, Group)", "summary": "Panel wraps content in a box. Padding adds whitespace. Group stacks renderables.", "difficulty": 2, "tags": ["layout"]},
            {"id": "logging", "type": "concept", "label": "RichHandler (logging integration)", "summary": "from rich.logging import RichHandler. Add to logging.basicConfig for pretty log output.", "difficulty": 2, "tags": ["logging"]},
            {"id": "inspect", "type": "function", "label": "rich.inspect()", "summary": "Introspect any Python object: shows attrs, methods, docstrings in a nicely formatted panel.", "difficulty": 1, "tags": ["debug", "common"]},
        ],
        "edges": [
            {"id": "e1", "from": "rich", "to": "Console", "label": "contains"},
            {"id": "e2", "from": "rich", "to": "Table", "label": "contains"},
            {"id": "e3", "from": "rich", "to": "Progress", "label": "contains"},
            {"id": "e4", "from": "rich", "to": "Syntax", "label": "contains"},
            {"id": "e5", "from": "rich", "to": "Traceback", "label": "contains"},
            {"id": "e6", "from": "rich", "to": "inspect", "label": "contains"},
            {"id": "e7", "from": "Console", "to": "markup", "label": "renders"},
            {"id": "e8", "from": "Console", "to": "Table", "label": "renders"},
            {"id": "e9", "from": "Console", "to": "Syntax", "label": "renders"},
            {"id": "e10", "from": "Console", "to": "Padding", "label": "renders"},
            {"id": "e11", "from": "rich", "to": "logging", "label": "contains"},
        ],
    },

    "react-query": {
        "nodes": [
            {"id": "react-query", "type": "module", "label": "@tanstack/react-query", "summary": "Import from '@tanstack/react-query'. Provides hooks for async state management.", "difficulty": 1, "tags": ["entry-point"]},
            {"id": "QueryClient", "type": "class", "label": "QueryClient", "summary": "Central cache store. Create once: `const queryClient = new QueryClient()`. Configure defaults.", "difficulty": 1, "tags": ["core"]},
            {"id": "QueryClientProvider", "type": "component", "label": "QueryClientProvider", "summary": "Wrap app root: `<QueryClientProvider client={queryClient}>`. Makes client available to all hooks.", "difficulty": 1, "tags": ["setup", "common"]},
            {"id": "useQuery", "type": "function", "label": "useQuery()", "summary": "Fetch and cache async data. `useQuery({ queryKey: ['todos'], queryFn: fetchTodos })`. Returns { data, isLoading, error }.", "difficulty": 1, "tags": ["query", "common"]},
            {"id": "useMutation", "type": "function", "label": "useMutation()", "summary": "Trigger create/update/delete ops. Returns { mutate, isPending }. Use onSuccess to invalidate queries.", "difficulty": 2, "tags": ["mutation", "common"]},
            {"id": "useInfiniteQuery", "type": "function", "label": "useInfiniteQuery()", "summary": "Paginated data: returns pages array, hasNextPage, fetchNextPage. For infinite scroll.", "difficulty": 2, "tags": ["pagination"]},
            {"id": "queryKey", "type": "concept", "label": "Query Keys", "summary": "Array-based cache keys: ['user', id]. Hierarchical invalidation: invalidateQueries(['user']) clears all user queries.", "difficulty": 2, "tags": ["cache", "common"]},
            {"id": "staleTime", "type": "concept", "label": "staleTime & gcTime", "summary": "staleTime: how long data is fresh (no refetch). gcTime: how long inactive cache lives.", "difficulty": 2, "tags": ["cache"]},
            {"id": "prefetch", "type": "function", "label": "queryClient.prefetchQuery()", "summary": "Pre-populate cache on the server or before navigation to avoid loading states.", "difficulty": 2, "tags": ["ssr"]},
            {"id": "devtools", "type": "concept", "label": "ReactQueryDevtools", "summary": "Import from '@tanstack/react-query-devtools'. Inspect cache, query states, and timings.", "difficulty": 1, "tags": ["devtools"]},
        ],
        "edges": [
            {"id": "e1", "from": "react-query", "to": "QueryClient", "label": "contains"},
            {"id": "e2", "from": "react-query", "to": "QueryClientProvider", "label": "contains"},
            {"id": "e3", "from": "react-query", "to": "useQuery", "label": "contains"},
            {"id": "e4", "from": "react-query", "to": "useMutation", "label": "contains"},
            {"id": "e5", "from": "react-query", "to": "useInfiniteQuery", "label": "contains"},
            {"id": "e6", "from": "QueryClientProvider", "to": "QueryClient", "label": "wraps"},
            {"id": "e7", "from": "useQuery", "to": "queryKey", "label": "uses"},
            {"id": "e8", "from": "useQuery", "to": "staleTime", "label": "configures"},
            {"id": "e9", "from": "QueryClient", "to": "prefetch", "label": "method"},
            {"id": "e10", "from": "useMutation", "to": "QueryClient", "label": "invalidates"},
        ],
    },

    "react-hook-form": {
        "nodes": [
            {"id": "react-hook-form", "type": "module", "label": "react-hook-form", "summary": "Import from 'react-hook-form'. Uncontrolled form validation library.", "difficulty": 1, "tags": ["entry-point"]},
            {"id": "useForm", "type": "function", "label": "useForm(options)", "summary": "Core hook. Returns { register, handleSubmit, watch, formState, setValue, getValues, reset, control }.", "difficulty": 1, "tags": ["core", "common"]},
            {"id": "register", "type": "function", "label": "register(name, rules)", "summary": "Connect an input to the form. Returns { ref, onChange, onBlur, name }. Supports validation rules.", "difficulty": 1, "tags": ["registration", "common"]},
            {"id": "handleSubmit", "type": "function", "label": "handleSubmit(onValid, onInvalid)", "summary": "Wraps form onSubmit. Validates first; calls onValid(data) on success.", "difficulty": 1, "tags": ["submit", "common"]},
            {"id": "formState", "type": "object", "label": "formState", "summary": "{ errors, isSubmitting, isValid, isDirty, dirtyFields, touchedFields }.", "difficulty": 1, "tags": ["state"]},
            {"id": "Controller", "type": "component", "label": "Controller", "summary": "Wrapper for controlled components (Select, DatePicker, etc.) that don't use native inputs.", "difficulty": 2, "tags": ["controlled"]},
            {"id": "useWatch", "type": "function", "label": "useWatch() / watch()", "summary": "Subscribe to field value changes. useWatch is more performant (targeted re-render).", "difficulty": 2, "tags": ["watch"]},
            {"id": "resolver", "type": "concept", "label": "Schema Resolvers (Zod, Yup, Joi)", "summary": "Pass resolver to useForm for schema validation: `resolver: zodResolver(schema)`. Auto-maps errors.", "difficulty": 2, "tags": ["validation", "common"]},
            {"id": "useFieldArray", "type": "function", "label": "useFieldArray()", "summary": "Manage dynamic arrays of fields: append, prepend, remove, move, swap.", "difficulty": 2, "tags": ["arrays"]},
        ],
        "edges": [
            {"id": "e1", "from": "react-hook-form", "to": "useForm", "label": "contains"},
            {"id": "e2", "from": "react-hook-form", "to": "Controller", "label": "contains"},
            {"id": "e3", "from": "react-hook-form", "to": "useFieldArray", "label": "contains"},
            {"id": "e4", "from": "useForm", "to": "register", "label": "returns"},
            {"id": "e5", "from": "useForm", "to": "handleSubmit", "label": "returns"},
            {"id": "e6", "from": "useForm", "to": "formState", "label": "returns"},
            {"id": "e7", "from": "useForm", "to": "useWatch", "label": "returns"},
            {"id": "e8", "from": "useForm", "to": "resolver", "label": "accepts"},
            {"id": "e9", "from": "register", "to": "formState", "label": "feeds-errors"},
        ],
    },

    "typescript": {
        "nodes": [
            {"id": "typescript", "type": "module", "label": "typescript (compiler API)", "summary": "The TypeScript compiler package. CLI: `tsc`. Programmatic API: `import ts from 'typescript'`.", "difficulty": 1, "tags": ["entry-point"]},
            {"id": "tsconfig", "type": "concept", "label": "tsconfig.json", "summary": "Project config: compilerOptions (target, module, strict, paths, baseUrl), include, exclude.", "difficulty": 1, "tags": ["config", "common"]},
            {"id": "types", "type": "concept", "label": "Type System Primitives", "summary": "string, number, boolean, null, undefined, symbol, bigint, unknown, never, any, void.", "difficulty": 1, "tags": ["types", "common"]},
            {"id": "generics", "type": "concept", "label": "Generics", "summary": "Parameterized types: `function identity<T>(x: T): T`. Constraints with extends. Default type params.", "difficulty": 2, "tags": ["generics", "common"]},
            {"id": "utility_types", "type": "concept", "label": "Utility Types", "summary": "Partial<T>, Required<T>, Readonly<T>, Pick<T,K>, Omit<T,K>, Record<K,V>, ReturnType<F>, Awaited<P>.", "difficulty": 2, "tags": ["types", "common"]},
            {"id": "unions_intersections", "type": "concept", "label": "Union & Intersection Types", "summary": "A | B (either), A & B (both). Discriminated unions with literal type tags.", "difficulty": 2, "tags": ["types"]},
            {"id": "mapped_types", "type": "concept", "label": "Mapped & Conditional Types", "summary": "{ [K in keyof T]: ... }. T extends U ? X : Y. infer keyword for type extraction.", "difficulty": 3, "tags": ["advanced"]},
            {"id": "decorators", "type": "concept", "label": "Decorators", "summary": "Experimental metadata annotations for classes, methods, properties. Enable with experimentalDecorators.", "difficulty": 3, "tags": ["advanced"]},
            {"id": "tsc_api", "type": "concept", "label": "Compiler API (ts.*)", "summary": "ts.createProgram(), ts.createSourceFile(), AST traversal with ts.forEachChild(), ts.Diagnostic.", "difficulty": 3, "tags": ["api"]},
            {"id": "declaration", "type": "concept", "label": "Declaration Files (.d.ts)", "summary": "Type-only files for JS libraries. Managed by @types/* on npm or authored manually.", "difficulty": 2, "tags": ["declarations"]},
        ],
        "edges": [
            {"id": "e1", "from": "typescript", "to": "tsconfig", "label": "configured-by"},
            {"id": "e2", "from": "typescript", "to": "types", "label": "provides"},
            {"id": "e3", "from": "typescript", "to": "generics", "label": "provides"},
            {"id": "e4", "from": "typescript", "to": "utility_types", "label": "provides"},
            {"id": "e5", "from": "typescript", "to": "unions_intersections", "label": "provides"},
            {"id": "e6", "from": "typescript", "to": "mapped_types", "label": "provides"},
            {"id": "e7", "from": "typescript", "to": "decorators", "label": "provides"},
            {"id": "e8", "from": "typescript", "to": "tsc_api", "label": "provides"},
            {"id": "e9", "from": "typescript", "to": "declaration", "label": "uses"},
            {"id": "e10", "from": "generics", "to": "utility_types", "label": "used-in"},
        ],
    },

    "click": {
        "nodes": [
            {"id": "click", "type": "module", "label": "click", "summary": "Import as `import click`. Decorator-based CLI framework.", "difficulty": 1, "tags": ["entry-point"]},
            {"id": "command", "type": "function", "label": "@click.command()", "summary": "Turn a function into a CLI command. Call with `python script.py` or via entry_points.", "difficulty": 1, "tags": ["command", "common"]},
            {"id": "group", "type": "function", "label": "@click.group()", "summary": "Create a command group (subcommands). `@group.command()` registers subcommands.", "difficulty": 1, "tags": ["command", "common"]},
            {"id": "option", "type": "function", "label": "@click.option()", "summary": "Declare optional flags/values: --name, --count, --flag/--no-flag. Types, defaults, prompts.", "difficulty": 1, "tags": ["params", "common"]},
            {"id": "argument", "type": "function", "label": "@click.argument()", "summary": "Positional arguments. Simpler than options — no flag, just positional.", "difficulty": 1, "tags": ["params"]},
            {"id": "types", "type": "concept", "label": "Parameter Types", "summary": "STRING, INT, FLOAT, BOOL, UUID, Path, File, DateTime, Choice, IntRange, FloatRange.", "difficulty": 2, "tags": ["types"]},
            {"id": "context", "type": "class", "label": "Context (ctx)", "summary": "Holds state per invocation. ctx.obj for shared state, ctx.invoke() to call other commands.", "difficulty": 2, "tags": ["context"]},
            {"id": "echo", "type": "function", "label": "click.echo() / click.style()", "summary": "click.echo() for output (handles encoding). click.style() for ANSI colours.", "difficulty": 1, "tags": ["output", "common"]},
            {"id": "progressbar", "type": "function", "label": "click.progressbar()", "summary": "Simple progress bar for iterables: `with click.progressbar(items) as bar: for item in bar:`.", "difficulty": 2, "tags": ["ui"]},
            {"id": "testing", "type": "class", "label": "CliRunner (testing)", "summary": "from click.testing import CliRunner. Invoke CLI commands in tests and capture output.", "difficulty": 2, "tags": ["testing"]},
        ],
        "edges": [
            {"id": "e1", "from": "click", "to": "command", "label": "contains"},
            {"id": "e2", "from": "click", "to": "group", "label": "contains"},
            {"id": "e3", "from": "click", "to": "option", "label": "contains"},
            {"id": "e4", "from": "click", "to": "argument", "label": "contains"},
            {"id": "e5", "from": "click", "to": "echo", "label": "contains"},
            {"id": "e6", "from": "click", "to": "progressbar", "label": "contains"},
            {"id": "e7", "from": "click", "to": "testing", "label": "contains"},
            {"id": "e8", "from": "command", "to": "option", "label": "decorated-with"},
            {"id": "e9", "from": "command", "to": "argument", "label": "decorated-with"},
            {"id": "e10", "from": "option", "to": "types", "label": "uses"},
            {"id": "e11", "from": "group", "to": "command", "label": "contains"},
            {"id": "e12", "from": "command", "to": "context", "label": "receives"},
        ],
    },

    "polars": {
        "nodes": [
            {"id": "polars", "type": "module", "label": "polars", "summary": "Import as `import polars as pl`. Rust-backed DataFrame library.", "difficulty": 1, "tags": ["entry-point"]},
            {"id": "DataFrame", "type": "class", "label": "DataFrame", "summary": "Immutable columnar data structure. All operations are lazy-friendly and return new DataFrames.", "difficulty": 1, "tags": ["core", "common"]},
            {"id": "LazyFrame", "type": "class", "label": "LazyFrame", "summary": "Lazy API: df.lazy() → chain operations → .collect(). Polars optimizes the full query plan.", "difficulty": 2, "tags": ["lazy", "common"]},
            {"id": "Series", "type": "class", "label": "Series", "summary": "Single typed column. Supports vectorized operations, Expr-compatible.", "difficulty": 1, "tags": ["core"]},
            {"id": "Expr", "type": "class", "label": "Expr (expressions)", "summary": "pl.col('name'), pl.lit(1), pl.when(cond).then(a).otherwise(b). Expressions compose into queries.", "difficulty": 2, "tags": ["expr", "common"]},
            {"id": "read_io", "type": "function", "label": "pl.read_csv / read_parquet / read_json", "summary": "Fast I/O readers. Also scan_csv / scan_parquet for lazy loading.", "difficulty": 1, "tags": ["io", "common"]},
            {"id": "groupby_agg", "type": "concept", "label": "group_by().agg()", "summary": "Grouped aggregations: .group_by('col').agg([pl.col('val').sum(), pl.col('x').mean()]).", "difficulty": 2, "tags": ["agg"]},
            {"id": "join", "type": "function", "label": "DataFrame.join()", "summary": "Join operations: inner, left, right, full, semi, anti, cross. Very fast on large data.", "difficulty": 2, "tags": ["join"]},
            {"id": "dtypes", "type": "concept", "label": "Data Types (pl.Int64, pl.Utf8…)", "summary": "Strict typing: Int8-Int64, Float32/64, Boolean, Utf8, Date, Datetime, Duration, List, Struct.", "difficulty": 2, "tags": ["types"]},
            {"id": "context", "type": "concept", "label": "Context (select / with_columns / filter)", "summary": "df.select([exprs]) replaces cols, .with_columns() adds, .filter(expr) filters rows.", "difficulty": 1, "tags": ["query", "common"]},
        ],
        "edges": [
            {"id": "e1", "from": "polars", "to": "DataFrame", "label": "core"},
            {"id": "e2", "from": "polars", "to": "LazyFrame", "label": "core"},
            {"id": "e3", "from": "polars", "to": "Series", "label": "core"},
            {"id": "e4", "from": "polars", "to": "Expr", "label": "core"},
            {"id": "e5", "from": "polars", "to": "read_io", "label": "contains"},
            {"id": "e6", "from": "DataFrame", "to": "LazyFrame", "label": "via-lazy()"},
            {"id": "e7", "from": "LazyFrame", "to": "DataFrame", "label": "via-collect()"},
            {"id": "e8", "from": "DataFrame", "to": "groupby_agg", "label": "method"},
            {"id": "e9", "from": "DataFrame", "to": "join", "label": "method"},
            {"id": "e10", "from": "DataFrame", "to": "context", "label": "method"},
            {"id": "e11", "from": "context", "to": "Expr", "label": "uses"},
        ],
    },

    "sqlalchemy": {
        "nodes": [
            {"id": "sqlalchemy", "type": "module", "label": "sqlalchemy", "summary": "Import from sqlalchemy. Two APIs: Core (SQL builder) and ORM (object mapping).", "difficulty": 1, "tags": ["entry-point"]},
            {"id": "engine", "type": "function", "label": "create_engine(url)", "summary": "Database connection factory: `engine = create_engine('postgresql://...')`. Manages connection pool.", "difficulty": 1, "tags": ["connection", "common"]},
            {"id": "Session", "type": "class", "label": "Session / sessionmaker", "summary": "ORM unit-of-work. Use with `with Session(engine) as session:`. Tracks changes, flushes, commits.", "difficulty": 1, "tags": ["orm", "common"]},
            {"id": "Base", "type": "class", "label": "DeclarativeBase", "summary": "ORM model base: `class MyModel(Base): __tablename__ = 'table'`. Maps Python class to DB table.", "difficulty": 1, "tags": ["orm", "common"]},
            {"id": "Column", "type": "class", "label": "Column / mapped_column", "summary": "Define table columns: `Column(String, primary_key=True)` or typed `mapped_column(int, nullable=False)`.", "difficulty": 1, "tags": ["orm"]},
            {"id": "relationship", "type": "function", "label": "relationship()", "summary": "ORM associations: one-to-many, many-to-many. lazy='select'/'joined'/'subquery'/'dynamic'.", "difficulty": 2, "tags": ["orm"]},
            {"id": "select", "type": "function", "label": "select() (Core + ORM)", "summary": "Build SELECT: `stmt = select(User).where(User.age > 18).order_by(User.name)`.", "difficulty": 1, "tags": ["query", "common"]},
            {"id": "execute", "type": "function", "label": "session.execute() / conn.execute()", "summary": "Run a statement. `result = session.execute(stmt)`. Use .scalars(), .all(), .one() to fetch.", "difficulty": 1, "tags": ["query"]},
            {"id": "migration", "type": "concept", "label": "Alembic (migrations)", "summary": "SQLAlchemy pairs with Alembic for schema migrations: alembic init, revision --autogenerate, upgrade.", "difficulty": 2, "tags": ["migration"]},
            {"id": "async_support", "type": "concept", "label": "Async (create_async_engine)", "summary": "from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession. Full async support.", "difficulty": 3, "tags": ["async"]},
        ],
        "edges": [
            {"id": "e1", "from": "sqlalchemy", "to": "engine", "label": "contains"},
            {"id": "e2", "from": "sqlalchemy", "to": "Session", "label": "contains"},
            {"id": "e3", "from": "sqlalchemy", "to": "Base", "label": "contains"},
            {"id": "e4", "from": "sqlalchemy", "to": "select", "label": "contains"},
            {"id": "e5", "from": "engine", "to": "Session", "label": "backs"},
            {"id": "e6", "from": "Base", "to": "Column", "label": "uses"},
            {"id": "e7", "from": "Base", "to": "relationship", "label": "uses"},
            {"id": "e8", "from": "Session", "to": "execute", "label": "method"},
            {"id": "e9", "from": "Session", "to": "select", "label": "executes"},
            {"id": "e10", "from": "sqlalchemy", "to": "migration", "label": "pairs-with"},
            {"id": "e11", "from": "sqlalchemy", "to": "async_support", "label": "supports"},
        ],
    },

    "immer": {
        "nodes": [
            {"id": "immer", "type": "module", "label": "immer", "summary": "Import from 'immer'. Immutable state via structural sharing.", "difficulty": 1, "tags": ["entry-point"]},
            {"id": "produce", "type": "function", "label": "produce(base, recipe)", "summary": "Core API. Receive a draft (mutable proxy) in recipe; return new immutable state. `produce(state, draft => { draft.x = 1 })`.", "difficulty": 1, "tags": ["core", "common"]},
            {"id": "Draft", "type": "concept", "label": "Draft<T>", "summary": "Mutable proxy of your state inside a producer. Changes tracked via Proxy. TypeScript: Draft<T> type.", "difficulty": 1, "tags": ["types"]},
            {"id": "current", "type": "function", "label": "current(draft)", "summary": "Snapshot the draft's current value (plain object) inside a recipe for logging/debugging.", "difficulty": 2, "tags": ["debug"]},
            {"id": "original", "type": "function", "label": "original(draft)", "summary": "Get the original (pre-mutation) value of a draft node.", "difficulty": 2, "tags": ["debug"]},
            {"id": "freeze", "type": "function", "label": "freeze(obj)", "summary": "Deep-freeze an object to prevent accidental mutation outside Immer.", "difficulty": 2, "tags": ["utility"]},
            {"id": "enableMapSet", "type": "function", "label": "enableMapSet()", "summary": "Enable Map and Set support in Immer (not included by default for bundle size).", "difficulty": 2, "tags": ["config"]},
            {"id": "patches", "type": "concept", "label": "Patches (undo/redo)", "summary": "produceWithPatches() returns [nextState, patches, inversePatches]. Apply with applyPatches().", "difficulty": 3, "tags": ["advanced"]},
            {"id": "curried", "type": "concept", "label": "Curried Producers", "summary": "`const updater = produce(recipe)` — returns a reusable function that accepts base state.", "difficulty": 2, "tags": ["patterns"]},
        ],
        "edges": [
            {"id": "e1", "from": "immer", "to": "produce", "label": "contains"},
            {"id": "e2", "from": "immer", "to": "current", "label": "contains"},
            {"id": "e3", "from": "immer", "to": "original", "label": "contains"},
            {"id": "e4", "from": "immer", "to": "freeze", "label": "contains"},
            {"id": "e5", "from": "immer", "to": "enableMapSet", "label": "contains"},
            {"id": "e6", "from": "immer", "to": "patches", "label": "contains"},
            {"id": "e7", "from": "produce", "to": "Draft", "label": "provides"},
            {"id": "e8", "from": "produce", "to": "curried", "label": "supports"},
            {"id": "e9", "from": "current", "to": "Draft", "label": "reads"},
        ],
    },

    "socket.io": {
        "nodes": [
            {"id": "socket.io", "type": "module", "label": "socket.io", "summary": "Server: `import { Server } from 'socket.io'`. Client: `import io from 'socket.io-client'`.", "difficulty": 1, "tags": ["entry-point"]},
            {"id": "Server", "type": "class", "label": "Server (io)", "summary": "Attach to HTTP server: `const io = new Server(httpServer)`. Manage namespaces, rooms, middleware.", "difficulty": 1, "tags": ["server", "common"]},
            {"id": "connection", "type": "concept", "label": "connection event", "summary": "`io.on('connection', socket => { ... })` fires for each new client. socket is the per-client handle.", "difficulty": 1, "tags": ["events", "common"]},
            {"id": "Socket_server", "type": "class", "label": "Socket (server-side)", "summary": "Per-client object: socket.emit(), socket.on(), socket.join(room), socket.id, socket.rooms.", "difficulty": 1, "tags": ["server"]},
            {"id": "emit", "type": "concept", "label": "Emitting Events", "summary": "socket.emit('event', data) → one client. io.emit() → all. io.to(room).emit() → room members.", "difficulty": 1, "tags": ["events", "common"]},
            {"id": "rooms", "type": "concept", "label": "Rooms", "summary": "socket.join('room')/leave('room'). Broadcast to rooms: io.to('room').emit(). Server-side concept only.", "difficulty": 2, "tags": ["rooms"]},
            {"id": "namespace", "type": "concept", "label": "Namespaces", "summary": "`io.of('/admin')` creates a scoped channel. Clients connect to `io('/admin')`. Separate event buses.", "difficulty": 2, "tags": ["namespace"]},
            {"id": "middleware_sio", "type": "concept", "label": "Middleware", "summary": "`io.use((socket, next) => { ... next() })` for auth/session. Runs before connection event.", "difficulty": 2, "tags": ["middleware"]},
            {"id": "client", "type": "class", "label": "Client (socket.io-client)", "summary": "`const socket = io('http://server')`. socket.emit(), socket.on(), socket.disconnect().", "difficulty": 1, "tags": ["client", "common"]},
            {"id": "ack", "type": "concept", "label": "Acknowledgements", "summary": "Request-response over WS: socket.emit('event', data, callback). Server calls the callback.", "difficulty": 2, "tags": ["advanced"]},
        ],
        "edges": [
            {"id": "e1", "from": "socket.io", "to": "Server", "label": "contains"},
            {"id": "e2", "from": "socket.io", "to": "client", "label": "contains"},
            {"id": "e3", "from": "Server", "to": "connection", "label": "emits"},
            {"id": "e4", "from": "connection", "to": "Socket_server", "label": "provides"},
            {"id": "e5", "from": "Socket_server", "to": "emit", "label": "method"},
            {"id": "e6", "from": "Socket_server", "to": "rooms", "label": "method"},
            {"id": "e7", "from": "Server", "to": "namespace", "label": "method"},
            {"id": "e8", "from": "Server", "to": "middleware_sio", "label": "method"},
            {"id": "e9", "from": "emit", "to": "ack", "label": "supports"},
        ],
    },

    "uuid": {
        "nodes": [
            {"id": "uuid", "type": "module", "label": "uuid", "summary": "Import named exports: `import { v1, v4, v5, validate, version, parse, stringify } from 'uuid'`.", "difficulty": 1, "tags": ["entry-point"]},
            {"id": "v4", "type": "function", "label": "v4()", "summary": "Generate a random UUID (RFC 4122). Most common use case. `uuid.v4()` → '110ec58a-a0f4-...'.", "difficulty": 1, "tags": ["generation", "common"]},
            {"id": "v1", "type": "function", "label": "v1()", "summary": "Time-based UUID. Encodes timestamp + MAC address. Monotonically increasing, not random.", "difficulty": 2, "tags": ["generation"]},
            {"id": "v5", "type": "function", "label": "v5(name, namespace)", "summary": "Name-based UUID using SHA-1. Same inputs always produce same UUID. Namespaces: DNS, URL, OID, X500.", "difficulty": 2, "tags": ["generation"]},
            {"id": "v3", "type": "function", "label": "v3(name, namespace)", "summary": "Like v5 but uses MD5. Less collision-resistant; prefer v5.", "difficulty": 2, "tags": ["generation"]},
            {"id": "validate", "type": "function", "label": "validate(str)", "summary": "Returns true if string is a valid UUID (any version).", "difficulty": 1, "tags": ["validation"]},
            {"id": "version", "type": "function", "label": "version(uuid)", "summary": "Returns the UUID version number (1, 3, 4, or 5) from a UUID string.", "difficulty": 1, "tags": ["inspection"]},
            {"id": "parse_stringify", "type": "function", "label": "parse() / stringify()", "summary": "parse() converts UUID string → Uint8Array. stringify() converts back. For binary storage.", "difficulty": 2, "tags": ["binary"]},
        ],
        "edges": [
            {"id": "e1", "from": "uuid", "to": "v4", "label": "contains"},
            {"id": "e2", "from": "uuid", "to": "v1", "label": "contains"},
            {"id": "e3", "from": "uuid", "to": "v5", "label": "contains"},
            {"id": "e4", "from": "uuid", "to": "v3", "label": "contains"},
            {"id": "e5", "from": "uuid", "to": "validate", "label": "contains"},
            {"id": "e6", "from": "uuid", "to": "version", "label": "contains"},
            {"id": "e7", "from": "uuid", "to": "parse_stringify", "label": "contains"},
            {"id": "e8", "from": "v4", "to": "validate", "label": "output-validated-by"},
            {"id": "e9", "from": "v1", "to": "version", "label": "identified-by"},
        ],
    },
}

# zustand needs special encoding treatment
GRAPHS["zustand"] = {
    "nodes": [
        {"id": "zustand", "type": "module", "label": "zustand", "summary": "Import as `import { create } from 'zustand'`. Minimal, unopinionated state management.", "difficulty": 1, "tags": ["entry-point"]},
        {"id": "create", "type": "function", "label": "create(initializer)", "summary": "Factory that returns a React hook: `const useStore = create((set, get) => ({ count: 0, inc: () => set(s => ({count: s.count+1})) }))`.", "difficulty": 1, "tags": ["core", "common"]},
        {"id": "useStore", "type": "function", "label": "useStore(selector?)", "summary": "React hook to access store state. `const count = useStore(s => s.count)`. Re-renders only when selection changes.", "difficulty": 1, "tags": ["hook", "common"]},
        {"id": "set", "type": "function", "label": "set(partial | updater)", "summary": "Update state. Partial: `set({ x: 1 })`. Updater: `set(state => ({ x: state.x + 1 }))`. Does shallow merge.", "difficulty": 1, "tags": ["update"]},
        {"id": "get", "type": "function", "label": "get()", "summary": "Read current state inside actions. Useful when you need current state inside an action closure.", "difficulty": 2, "tags": ["access"]},
        {"id": "subscribe", "type": "function", "label": "store.subscribe(listener)", "summary": "Subscribe to state changes outside React. Returns unsubscribe fn. Used in non-component code.", "difficulty": 2, "tags": ["subscribe"]},
        {"id": "persist", "type": "concept", "label": "persist middleware", "summary": "`create(persist(initializer, { name: 'my-store' }))` — auto-saves to localStorage/sessionStorage/custom.", "difficulty": 2, "tags": ["middleware", "common"]},
        {"id": "immer_mw", "type": "concept", "label": "immer middleware", "summary": "`create(immer(initializer))` — write mutable-style updates inside set. Uses Immer under the hood.", "difficulty": 2, "tags": ["middleware"]},
        {"id": "devtools", "type": "concept", "label": "devtools middleware", "summary": "`create(devtools(initializer))` — connect to Redux DevTools for time-travel debugging.", "difficulty": 2, "tags": ["devtools"]},
        {"id": "shallow", "type": "function", "label": "shallow (equality)", "summary": "import shallow from 'zustand/shallow'. Use as second arg to useStore to prevent unnecessary re-renders when selecting multiple values.", "difficulty": 2, "tags": ["performance"]},
    ],
    "edges": [
        {"id": "e1", "from": "zustand", "to": "create", "label": "contains"},
        {"id": "e2", "from": "create", "to": "useStore", "label": "returns"},
        {"id": "e3", "from": "create", "to": "set", "label": "provides"},
        {"id": "e4", "from": "create", "to": "get", "label": "provides"},
        {"id": "e5", "from": "useStore", "to": "subscribe", "label": "method"},
        {"id": "e6", "from": "zustand", "to": "persist", "label": "middleware"},
        {"id": "e7", "from": "zustand", "to": "immer_mw", "label": "middleware"},
        {"id": "e8", "from": "zustand", "to": "devtools", "label": "middleware"},
        {"id": "e9", "from": "useStore", "to": "shallow", "label": "uses"},
    ],
}


def fix_package(name: str, graph: dict) -> None:
    path = os.path.join(DATA_DIR, f"{name}.json")
    if not os.path.exists(path):
        print(f"  SKIP (not found): {name}")
        return
    try:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
    except UnicodeDecodeError:
        with open(path, encoding="cp1252") as f:
            data = json.load(f)
    data["graph"] = graph
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"  OK: {name} — {len(graph['nodes'])} nodes, {len(graph['edges'])} edges")


if __name__ == "__main__":
    print("Fixing API maps...")
    for pkg_name, graph_data in GRAPHS.items():
        fix_package(pkg_name, graph_data)
    print("Done.")
